#theme: jekyll-theme-cayman

# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          DeokYeon.kim
paginate:       5
baseurl:        ""
url:            "https://dochoul.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Gems
gems:
  - jekyll-paginate
